export enum CustomFieldsTypeEnum {
    text = 'text',
    numeric = 'numeric',
    checkbox = 'checkbox',
    select = 'select',
    multiselect = 'multiselect',
    date = 'date',
    url = 'url',
    textarea = 'textarea',
    radiobutton = 'radiobutton',
    streetaddress = 'streetaddress',
    smart_address = 'smart_address',
    birthday = 'birthday',
    legal_entity = 'legal_entity',
    date_time = 'date_time',
    price = 'price',
    category = 'category',
    items = 'items',
    tracking_data = 'tracking_data',
    linked_entity = 'linked_entity',
    chained_list = 'chained_list',
    monetary = 'monetary',
    file = 'file',
    payer = 'payer',
    supplier = 'supplier',
}